find_trending_companies:
  description: >
    Scan the latest Indian financial news and identify 2-3 companies trending in the {sector}.
    Prioritize companies impacted by recent policy changes (e.g., GST 2.0), IPO announcements, or sector-specific developments.
    Always select new companies not previously identified.
  expected_output: >
    A list of trending Indian companies in the {sector}, including brief context on why each is trending.
  agent: trending_company_finder
  output_file: output/trending_companies.json

research_trending_companies:
  description: >
    Given a list of trending Indian companies, conduct detailed research on each.
    Include financial performance, sector outlook, recent news drivers, and macroeconomic or regulatory influences.
    Use credible Indian sources like Moneycontrol, Economic Times, Mint, and company filings.
  expected_output: >
    A structured report analyzing each company's fundamentals, recent developments, and investment relevance.
  agent: financial_researcher
  context:
    - find_trending_companies
  output_file: output/research_report.json

pick_best_company:
  description: >
    Review the research and select the most promising Indian company for investment.
    Send a push notification to the user with the selected company and a one-line rationale.
    Then provide a detailed report explaining the selection, including comparative analysis of companies not chosen.
    Consider valuation, growth potential, sector momentum, and policy tailwinds.
  expected_output: >
    The selected company with rationale, plus a breakdown of why other companies were not selected.
  agent: stock_picker
  context:
    - research_trending_companies
  output_file: output/decision.md
